name: hexlet-ci
on: push
jobs:

  security:
        runs-on: ubuntu-latest
        steps:
          - name: check env
            run: env 
          - uses: actions/checkout@master
          - name: Run Snyk to check for vulnerabilities
            uses: snyk/actions/node@master
            env:
              SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2  

      - name: setup project
        run: make setup

      - name: tests
        run: make test

      - name: lint
        run: make lint