name: hexlet-ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: run snyk for check 
        uses: snyk/actions/checkout@main
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: setup project
        run: make setup

      - name: tests
        run: make test

      - name: lint
        run: make lint